"""Add MongoDB GridFS media columns

Revision ID: 6e48922ca894
Revises: a1b2c3d4e5f6
Create Date: 2026-10-07 15:19:58.563159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e48922ca894'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_content_items'), 'content_items', type_='unique')
    op.create_index(op.f('ix_content_items_generation_date'), 'content_items', ['generation_date'], unique=False)
    op.create_unique_constraint('uq_content_items_v2', 'content_items', ['property_id', 'generation_date', 'kind', 'variant_number', 'platform', 'language'])
    op.add_column('generated_media', sa.Column('storage_key', sa.String(), nullable=True))
    op.add_column('generated_media', sa.Column('file_token', sa.String(), nullable=True))
    op.add_column('generated_media', sa.Column('size_bytes', sa.Integer(), nullable=True))
    op.add_column('generated_media', sa.Column('sha256', sa.String(), nullable=True))
    op.create_index(op.f('ix_generated_media_file_token'), 'generated_media', ['file_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generated_media_file_token'), table_name='generated_media')
    op.drop_column('generated_media', 'sha256')
    op.drop_column('generated_media', 'size_bytes')
    op.drop_column('generated_media', 'file_token')
    op.drop_column('generated_media', 'storage_key')
    op.drop_constraint('uq_content_items_v2', 'content_items', type_='unique')
    op.drop_index(op.f('ix_content_items_generation_date'), table_name='content_items')
    op.create_unique_constraint(op.f('uq_content_items'), 'content_items', ['property_id', 'kind', 'platform', 'scheduled_at', 'language'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
